version: 2
jobs:
  build:
    docker:
      - image: blurrcat/docker-elm-build:0.19
    working_directory: ~/reader
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-{{ checksum "package.json" }}-v2
            - elm-19-{{ checksum "elm.json" }}-v2
      - run: |
          npm install
      - run: |
          sysconfcpus -n 1 npm run build
      - save_cache:
          key: node-{{ checksum "package.json" }}-v2
          paths:
            - "./node_modules"
      - save_cache:
          key: elm-19-{{ checksum "elm.json" }}-v2
          paths:
            - "./elm-stuff"
            - "/root/.elm"
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              cat >> ~/.ssh/config << EOF
              VerifyHostKeyDNS yes
              StrictHostKeyChecking no
            EOF
              git remote add dokku dokku@seattle.blurrcat.net:reader
              git config user.name "blurrcat"
              git config user.email "blurrcat@gmail.com"
              ./deploy.sh
            fi
